// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Answer
{
    public string AnswerId { get; set; }

    public string QuestionId { get; set; }

    public string OptionText { get; set; }

    public string OptionType { get; set; }

    public DateTime? CreateAt { get; set; }

    public bool? IsCorrect { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<EnrollAnswer> EnrollAnswers { get; set; } = new List<EnrollAnswer>();

    public virtual Question Question { get; set; }
}