// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Attachment
{
    public string AttachmentId { get; set; }

    public string Status { get; set; }

    public string DocNo { get; set; }

    public string AttachmentName { get; set; }

    public string AttachmentUrl { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string OtpCode { get; set; }

    public DateTime? OtpExpiredTime { get; set; }

    public string CreateBy { get; set; }

    public virtual ICollection<BookingOffline> BookingOfflines { get; set; } = new List<BookingOffline>();
}