// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class BookingOffline
{
    public string BookingOfflineId { get; set; }

    public string CustomerId { get; set; }

    public string MasterId { get; set; }

    public string ConsultationPackageId { get; set; }

    public string ContractId { get; set; }

    public string DocumentId { get; set; }

    public string RecordId { get; set; }

    public string Location { get; set; }

    public string Status { get; set; }

    public string Description { get; set; }

    public string MasterScheduleId { get; set; }

    public string AssignStaffId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public decimal? SelectedPrice { get; set; }

    public virtual Account AssignStaff { get; set; }

    public virtual ICollection<Attachment> Attachments { get; set; } = new List<Attachment>();

    public virtual ConsultationPackage ConsultationPackage { get; set; }

    public virtual Contract Contract { get; set; }

    public virtual ICollection<Contract> Contracts { get; set; } = new List<Contract>();

    public virtual Customer Customer { get; set; }

    public virtual FengShuiDocument Document { get; set; }

    public virtual ICollection<FengShuiDocument> FengShuiDocuments { get; set; } = new List<FengShuiDocument>();

    public virtual Master Master { get; set; }

    public virtual MasterSchedule MasterSchedule { get; set; }

    public virtual Attachment Record { get; set; }
}