// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class BookingOnline
{
    public string BookingOnlineId { get; set; }

    public string LinkMeet { get; set; }

    public string Status { get; set; }

    public string MasterId { get; set; }

    public string CustomerId { get; set; }

    public string Description { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Master Master { get; set; }
}