// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Category
{
    public string CategoryId { get; set; }

    public string CategoryName { get; set; }

    public string ImageUrl { get; set; }

    public string Status { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}