// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Certificate
{
    public string CertificateId { get; set; }

    public DateOnly? IssueDate { get; set; }

    public string Description { get; set; }

    public string CertificateImage { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    public virtual ICollection<EnrollCert> EnrollCerts { get; set; } = new List<EnrollCert>();
}