// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Color
{
    public string ColorId { get; set; }

    public string ColorName { get; set; }

    public string ColorCode { get; set; }

    public string Element { get; set; }
     
    public virtual ICollection<VarietyColor> VarietyColors { get; set; } = new List<VarietyColor>();
}