// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class ConsultationPackage
{
    public string ConsultationPackageId { get; set; }

    public string PackageName { get; set; }

    public decimal? MinPrice { get; set; }

    public decimal? MaxPrice { get; set; }

    public string Description { get; set; }

    public string SuitableFor { get; set; }

    public string RequiredInfo { get; set; }

    public string PricingDetails { get; set; }

    public string ImageUrl { get; set; }

    public virtual ICollection<BookingOffline> BookingOfflines { get; set; } = new List<BookingOffline>();
}