// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Contract
{
    public string ContractId { get; set; }

    public string Status { get; set; }

    public string DocNo { get; set; }

    public string ContractName { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string OtpCode { get; set; }

    public DateTime? OtpExpiredTime { get; set; }

    public string ContractUrl { get; set; }

    public string BookingOfflineId { get; set; }

    public virtual BookingOffline BookingOffline { get; set; }

}