// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Course
{
    public string CourseId { get; set; }

    public string CourseName { get; set; }

    public decimal? Rating { get; set; }

    public bool? IsBestSeller { get; set; }

    public string Status { get; set; }

    public string CertificateId { get; set; }

    public string QuizId { get; set; }

    public decimal? Price { get; set; }

    public DateTime CreateAt { get; set; }

    public string CreateBy { get; set; }

    public DateTime? UpdateAt { get; set; }

    public string Description { get; set; }

    public string ImageUrl { get; set; }

    public string CategoryId { get; set; }

    public string Introduction { get; set; }

    public virtual Category Category { get; set; }

    public virtual Certificate Certificate { get; set; }

    public virtual ICollection<Chapter> Chapters { get; set; } = new List<Chapter>();

    public virtual Master CreateByNavigation { get; set; }

    public virtual Quiz Quiz { get; set; }

    public virtual ICollection<Quiz> Quizzes { get; set; } = new List<Quiz>();

    public virtual ICollection<RegisterCourse> RegisterCourses { get; set; } = new List<RegisterCourse>();
}