// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Customer
{
    public string CustomerId { get; set; }

    public string LifePalace { get; set; }

    public string Element { get; set; }

    public string AccountId { get; set; }

    public string MembershipId { get; set; }

    public string ImageUrl { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<BookingOffline> BookingOfflines { get; set; } = new List<BookingOffline>();

    public virtual ICollection<BookingOnline> BookingOnlines { get; set; } = new List<BookingOnline>();

    public virtual ICollection<EnrollCert> EnrollCerts { get; set; } = new List<EnrollCert>();

    public virtual ICollection<EnrollQuiz> EnrollQuizzes { get; set; } = new List<EnrollQuiz>();

    public virtual Membership Membership { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<RegisterAttend> RegisterAttends { get; set; } = new List<RegisterAttend>();

    public virtual ICollection<RegisterCourse> RegisterCourses { get; set; } = new List<RegisterCourse>();
}