// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class ElementPoint
{
    public string ElementType { get; set; }

    public double? Point { get; set; }
}