// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class EnrollQuiz
{
    public string EnrollQuizId { get; set; }

    public string QuizId { get; set; }

    public decimal? Point { get; set; }

    public string ParticipantId { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<EnrollAnswer> EnrollAnswers { get; set; } = new List<EnrollAnswer>();

    public virtual Customer Participant { get; set; }

    public virtual Quiz Quiz { get; set; }

    public virtual ICollection<RegisterCourse> RegisterCourses { get; set; } = new List<RegisterCourse>();
}