// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class EnrollAnswer
{
    public string EnrollAnswerId { get; set; }

    public string AnswerId { get; set; }

    public bool? Correct { get; set; }

    public virtual Answer Answer { get; set; }

    public virtual ICollection<EnrollQuiz> EnrollQuizzes { get; set; } = new List<EnrollQuiz>();
}