// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class EnrollCert
{
    public string EnrollCertId { get; set; }

    public string CertificateId { get; set; }

    public DateOnly? FinishDate { get; set; }

    public string CustomerId { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual Certificate Certificate { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<RegisterCourse> RegisterCourses { get; set; } = new List<RegisterCourse>();
}