// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class EnrollChapter
{
    public string EnrollChapterId { get; set; }

    public string ChapterId { get; set; }

    public string Status { get; set; }

    public string EnrollCourseId { get; set; }

    public virtual Chapter Chapter { get; set; }

    public virtual RegisterCourse EnrollCourse { get; set; }
}