// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class FengShuiDocument
{
    public string FengShuiDocumentId { get; set; }

    public string Version { get; set; }

    public string Status { get; set; }

    public string DocNo { get; set; }

    public string DocumentName { get; set; }

    public virtual ICollection<BookingOffline> BookingOfflines { get; set; } = new List<BookingOffline>();
}