// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace BusinessObjects.Models;

public partial class KoiFishPondContext : DbContext
{

    public KoiFishPondContext()
    {
    }

    public KoiFishPondContext(DbContextOptions<KoiFishPondContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<Answer> Answers { get; set; }

    public virtual DbSet<Attachment> Attachments { get; set; }

    public virtual DbSet<BookingOffline> BookingOfflines { get; set; }

    public virtual DbSet<BookingOnline> BookingOnlines { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Certificate> Certificates { get; set; }

    public virtual DbSet<Chapter> Chapters { get; set; }

    public virtual DbSet<Color> Colors { get; set; }

    public virtual DbSet<CompatibilityPoint> CompatibilityPoints { get; set; }

    public virtual DbSet<ConsultationPackage> ConsultationPackages { get; set; }

    public virtual DbSet<Contract> Contracts { get; set; }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<ElementPoint> ElementPoints { get; set; }

    public virtual DbSet<EnrollAnswer> EnrollAnswers { get; set; }

    public virtual DbSet<EnrollCert> EnrollCerts { get; set; }

    public virtual DbSet<EnrollChapter> EnrollChapters { get; set; }

    public virtual DbSet<EnrollQuiz> EnrollQuizzes { get; set; }

    public virtual DbSet<FengShuiDocument> FengShuiDocuments { get; set; }

    public virtual DbSet<KoiPond> KoiPonds { get; set; }

    public virtual DbSet<KoiVariety> KoiVarieties { get; set; }

    public virtual DbSet<Location> Locations { get; set; }

    public virtual DbSet<MansionsPoint> MansionsPoints { get; set; }

    public virtual DbSet<Master> Masters { get; set; }

    public virtual DbSet<MasterSchedule> MasterSchedules { get; set; }

    public virtual DbSet<Membership> Memberships { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<Question> Questions { get; set; }

    public virtual DbSet<Quiz> Quizzes { get; set; }

    public virtual DbSet<RegisterAttend> RegisterAttends { get; set; }

    public virtual DbSet<RegisterCourse> RegisterCourses { get; set; }

    public virtual DbSet<Shape> Shapes { get; set; }

    public virtual DbSet<VarietyColor> VarietyColors { get; set; }

    public virtual DbSet<WorkShop> WorkShops { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var envConnectionString = Environment.GetEnvironmentVariable(connectionStringName);
        if (!string.IsNullOrEmpty(envConnectionString))
            return envConnectionString;

        var config = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json", optional: true)
            .Build();
        return config.GetConnectionString(connectionStringName);
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        var connectionString = GetConnectionString("DefaultConnection");
        if (string.IsNullOrEmpty(connectionString))
            throw new InvalidOperationException("Connection string 'DefaultConnection' không được tìm thấy.");

        optionsBuilder.UseSqlServer(connectionString);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("PK__Account__349DA5A606BA024A");

            entity.ToTable("Account");

            entity.Property(e => e.AccountId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.AccountName).HasMaxLength(255);
            entity.Property(e => e.AccountNo).HasMaxLength(19);
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.FullName).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Password).HasMaxLength(255);
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Role).HasMaxLength(20);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
            entity.Property(e => e.UserName).HasMaxLength(50);
        });

        modelBuilder.Entity<Answer>(entity =>
        {
            entity.HasKey(e => e.AnswerId).HasName("PK__Answer__D4825004008E39DA");

            entity.ToTable("Answer");

            entity.Property(e => e.AnswerId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateAt).HasColumnName("Create_At");
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.IsCorrect).HasColumnName("Is_Correct");
            entity.Property(e => e.OptionText).HasColumnName("Option_Text");
            entity.Property(e => e.OptionType)
                .HasMaxLength(50)
                .HasColumnName("Option_Type");
            entity.Property(e => e.QuestionId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.Question).WithMany(p => p.Answers)
                .HasForeignKey(d => d.QuestionId)
                .HasConstraintName("FK__Answer__Question__02084FDA");
        });

        modelBuilder.Entity<Attachment>(entity =>
        {
            entity.HasKey(e => e.AttachmentId).HasName("PK__Attachme__442C64BE465B1D76");

            entity.ToTable("Attachment");

            entity.Property(e => e.AttachmentId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.AttachmentName).HasMaxLength(100);
            entity.Property(e => e.AttachmentUrl).HasColumnName("AttachmentURL");
            entity.Property(e => e.CreateBy)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DocNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.OtpCode).HasMaxLength(10);
            entity.Property(e => e.OtpExpiredTime).HasColumnType("datetime");
            entity.Property(e => e.Status).HasMaxLength(255);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<BookingOffline>(entity =>
        {
            entity.HasKey(e => e.BookingOfflineId).HasName("PK__BookingO__37BA37039CB1981B");

            entity.ToTable("BookingOffline");

            entity.Property(e => e.BookingOfflineId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.AssignStaffId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.ConsultationPackageId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.ContractId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CustomerId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.DocumentId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Location).HasMaxLength(255);
            entity.Property(e => e.MasterId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.MasterScheduleId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.RecordId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.SelectedPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Status).HasMaxLength(255);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.AssignStaff).WithMany(p => p.BookingOfflines)
                .HasForeignKey(d => d.AssignStaffId)
                .HasConstraintName("FK_BookingOffline_AssignStaff");

            entity.HasOne(d => d.ConsultationPackage).WithMany(p => p.BookingOfflines)
                .HasForeignKey(d => d.ConsultationPackageId)
                .HasConstraintName("FK__BookingOf__Consu__02FC7413");

            entity.HasOne(d => d.Contract).WithMany(p => p.BookingOfflines)
                .HasForeignKey(d => d.ContractId)
                .HasConstraintName("FK__BookingOf__Contr__03F0984C");

            entity.HasOne(d => d.Customer).WithMany(p => p.BookingOfflines)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK__BookingOf__Custo__04E4BC85");

            entity.HasOne(d => d.Document).WithMany(p => p.BookingOfflines)
                .HasForeignKey(d => d.DocumentId)
                .HasConstraintName("FK__BookingOf__Docum__05D8E0BE");

            entity.HasOne(d => d.Master).WithMany(p => p.BookingOfflines)
                .HasForeignKey(d => d.MasterId)
                .HasConstraintName("FK__BookingOf__Maste__06CD04F7");

            entity.HasOne(d => d.MasterSchedule).WithMany(p => p.BookingOfflines)
                .HasForeignKey(d => d.MasterScheduleId)
                .HasConstraintName("FK_BookingOffline_MasterSchedule");

            entity.HasOne(d => d.Record).WithMany(p => p.BookingOfflines)
                .HasForeignKey(d => d.RecordId)
                .HasConstraintName("FK__BookingOf__Recor__07C12930");
        });

        modelBuilder.Entity<BookingOnline>(entity =>
        {
            entity.HasKey(e => e.BookingOnlineId).HasName("PK__BookingO__D0E9AFED6E036D58");

            entity.ToTable("BookingOnline");

            entity.Property(e => e.BookingOnlineId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.AssignStaffId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CustomerId)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.MasterId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.MasterNote).HasMaxLength(255);
            entity.Property(e => e.MasterScheduleId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.AssignStaff).WithMany(p => p.BookingOnlines)
                .HasForeignKey(d => d.AssignStaffId)
                .HasConstraintName("FK_BookingOnline_AssignStaff");

            entity.HasOne(d => d.Customer).WithMany(p => p.BookingOnlines)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingOnline_Customer");

            entity.HasOne(d => d.Master).WithMany(p => p.BookingOnlines)
                .HasForeignKey(d => d.MasterId)
                .HasConstraintName("FK_BookingOnline_Master");

            entity.HasOne(d => d.MasterSchedule).WithMany(p => p.BookingOnlines)
                .HasForeignKey(d => d.MasterScheduleId)
                .HasConstraintName("FK_BookingOnline_MasterSchedule");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__Category__19093A0B57456A03");

            entity.ToTable("Category");

            entity.Property(e => e.CategoryId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.ImageUrl).HasMaxLength(255);
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Certificate>(entity =>
        {
            entity.HasKey(e => e.CertificateId).HasName("PK__Certific__BBF8A7C1DCAAA32F");

            entity.ToTable("Certificate");

            entity.Property(e => e.CertificateId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CertificateImage).HasMaxLength(255);
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Chapter>(entity =>
        {
            entity.HasKey(e => e.ChapterId).HasName("PK__Chapter__0893A36A2E89C123");

            entity.ToTable("Chapter");

            entity.Property(e => e.ChapterId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CourseId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Title).HasMaxLength(100);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
            entity.Property(e => e.Video).HasMaxLength(255);

            entity.HasOne(d => d.Course).WithMany(p => p.Chapters)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("FK__Chapter__CourseI__0E6E26BF");
        });

        modelBuilder.Entity<Color>(entity =>
        {
            entity.HasKey(e => e.ColorId).HasName("PK__Color__8DA7674D15DA98BD");

            entity.ToTable("Color");

            entity.Property(e => e.ColorId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.ColorCode)
                .HasMaxLength(7)
                .IsUnicode(false);
            entity.Property(e => e.ColorName).HasMaxLength(50);
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.Element).HasMaxLength(20);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<CompatibilityPoint>(entity =>
        {
            entity.HasKey(e => e.CompatibilityType).HasName("PK__Compatib__490B3B31FE35398B");

            entity.ToTable("CompatibilityPoint");

            entity.Property(e => e.CompatibilityType)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ConsultationPackage>(entity =>
        {
            entity.HasKey(e => e.ConsultationPackageId).HasName("PK__Consulta__3A64C5568A5FB642");

            entity.ToTable("ConsultationPackage");

            entity.Property(e => e.ConsultationPackageId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.ImageUrl).HasMaxLength(255);
            entity.Property(e => e.MaxPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MinPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PackageName).HasMaxLength(100);
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Contract>(entity =>
        {
            entity.HasKey(e => e.ContractId).HasName("PK__Contract__C90D34690EEC0B6D");

            entity.ToTable("Contract");

            entity.Property(e => e.ContractId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.ContractName).HasMaxLength(100);
            entity.Property(e => e.ContractUrl).HasMaxLength(255);
            entity.Property(e => e.CreateBy)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DocNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.OtpCode).HasMaxLength(50);
            entity.Property(e => e.OtpExpiredTime).HasColumnType("datetime");
            entity.Property(e => e.Status).HasMaxLength(255);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Course>(entity =>
        {
            entity.HasKey(e => e.CourseId).HasName("PK__Course__C92D71A7BC003238");

            entity.ToTable("Course");

            entity.Property(e => e.CourseId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CategoryId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CertificateId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CourseName).HasMaxLength(100);
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CreateBy)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.ImageUrl).HasMaxLength(255);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.QuizId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Rating).HasColumnType("decimal(3, 2)");
            entity.Property(e => e.Status).HasMaxLength(20);
            entity.Property(e => e.UpdateAt).HasColumnType("datetime");

            entity.HasOne(d => d.Category).WithMany(p => p.Courses)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_Course_Category");

            entity.HasOne(d => d.Certificate).WithMany(p => p.Courses)
                .HasForeignKey(d => d.CertificateId)
                .HasConstraintName("FK__Course__Certific__0F624AF8");

            entity.HasOne(d => d.CreateByNavigation).WithMany(p => p.Courses)
                .HasForeignKey(d => d.CreateBy)
                .HasConstraintName("FK_Course_Master");

            entity.HasOne(d => d.Quiz).WithMany(p => p.Courses)
                .HasForeignKey(d => d.QuizId)
                .HasConstraintName("FK__Course__QuizId__10566F31");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("PK__Customer__A4AE64D82CCE77E6");

            entity.ToTable("Customer");

            entity.Property(e => e.CustomerId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.AccountId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.Element).HasMaxLength(20);
            entity.Property(e => e.ImageUrl).HasMaxLength(255);
            entity.Property(e => e.LifePalace).HasMaxLength(20);
            entity.Property(e => e.MembershipId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.Account).WithMany(p => p.Customers)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK__Customer__Accoun__1332DBDC");

            entity.HasOne(d => d.Membership).WithMany(p => p.Customers)
                .HasForeignKey(d => d.MembershipId)
                .HasConstraintName("FK__Customer__Member__14270015");
        });

        modelBuilder.Entity<ElementPoint>(entity =>
        {
            entity.HasKey(e => e.ElementType).HasName("PK__ElementP__D7C667975ED45125");

            entity.ToTable("ElementPoint");

            entity.Property(e => e.ElementType)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CompatibleElement)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.IncompatibleElement)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<EnrollAnswer>(entity =>
        {
            entity.HasKey(e => e.EnrollAnswerId).HasName("PK__EnrollAn__913A38559E1AD26B");

            entity.ToTable("EnrollAnswer");

            entity.Property(e => e.EnrollAnswerId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.AnswerId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.EnrollQuizId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();

            entity.HasOne(d => d.Answer).WithMany(p => p.EnrollAnswers)
                .HasForeignKey(d => d.AnswerId)
                .HasConstraintName("FK__EnrollAns__Answe__151B244E");

            entity.HasOne(d => d.EnrollQuiz).WithMany(p => p.EnrollAnswers)
                .HasForeignKey(d => d.EnrollQuizId)
                .HasConstraintName("FK_EnrollAnswer_EnrollQuiz");
        });

        modelBuilder.Entity<EnrollCert>(entity =>
        {
            entity.HasKey(e => e.EnrollCertId).HasName("PK__EnrollCe__15C91EE94A2763DD");

            entity.ToTable("EnrollCert");

            entity.Property(e => e.EnrollCertId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CertificateId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.CustomerId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.Certificate).WithMany(p => p.EnrollCerts)
                .HasForeignKey(d => d.CertificateId)
                .HasConstraintName("FK__EnrollCer__Certi__17036CC0");

            entity.HasOne(d => d.Customer).WithMany(p => p.EnrollCerts)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK__EnrollCer__Custo__17F790F9");
        });

        modelBuilder.Entity<EnrollChapter>(entity =>
        {
            entity.HasKey(e => e.EnrollChapterId).HasName("PK__EnrollCh__035269FB33282F36");

            entity.ToTable("EnrollChapter");

            entity.Property(e => e.EnrollChapterId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.ChapterId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.EnrollCourseId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Status).HasMaxLength(20);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.Chapter).WithMany(p => p.EnrollChapters)
                .HasForeignKey(d => d.ChapterId)
                .HasConstraintName("FK__EnrollCha__Chapt__18EBB532");

            entity.HasOne(d => d.EnrollCourse).WithMany(p => p.EnrollChapters)
                .HasForeignKey(d => d.EnrollCourseId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_EnrollChapter_EnrollCourse");
        });

        modelBuilder.Entity<EnrollQuiz>(entity =>
        {
            entity.HasKey(e => e.EnrollQuizId).HasName("PK__EnrollQu__B842C36624F2AA7A");

            entity.ToTable("EnrollQuiz");

            entity.Property(e => e.EnrollQuizId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.ParticipantId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Point).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.QuizId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.Participant).WithMany(p => p.EnrollQuizzes)
                .HasForeignKey(d => d.ParticipantId)
                .HasConstraintName("FK__EnrollQui__Parti__1AD3FDA4");

            entity.HasOne(d => d.Quiz).WithMany(p => p.EnrollQuizzes)
                .HasForeignKey(d => d.QuizId)
                .HasConstraintName("FK__EnrollQui__QuizI__1BC821DD");
        });

        modelBuilder.Entity<FengShuiDocument>(entity =>
        {
            entity.HasKey(e => e.FengShuiDocumentId).HasName("PK__FengShui__AFCA4193366E8A4D");

            entity.ToTable("FengShuiDocument");

            entity.Property(e => e.FengShuiDocumentId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateBy)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DocNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DocumentName).HasMaxLength(100);
            entity.Property(e => e.DocumentUrl).HasColumnName("DocumentURL");
            entity.Property(e => e.Status).HasMaxLength(255);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
            entity.Property(e => e.Version)
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<KoiPond>(entity =>
        {
            entity.HasKey(e => e.KoiPondId).HasName("PK__KoiPond__8DAE659A9F21FA4D");

            entity.ToTable("KoiPond");

            entity.Property(e => e.KoiPondId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.ImageUrl).HasMaxLength(255);
            entity.Property(e => e.Introduction).HasMaxLength(255);
            entity.Property(e => e.PondName).HasMaxLength(100);
            entity.Property(e => e.ShapeId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.Shape).WithMany(p => p.KoiPonds)
                .HasForeignKey(d => d.ShapeId)
                .HasConstraintName("FK__KoiPond__ShapeId__1CBC4616");
        });

        modelBuilder.Entity<KoiVariety>(entity =>
        {
            entity.HasKey(e => e.KoiVarietyId).HasName("PK__KoiVarie__94DDFCB2DB7021C7");

            entity.ToTable("KoiVariety");

            entity.Property(e => e.KoiVarietyId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("KoiVarietyID");
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.ImageUrl).HasMaxLength(255);
            entity.Property(e => e.Introduction).HasMaxLength(255);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
            entity.Property(e => e.VarietyName).HasMaxLength(50);
        });

        modelBuilder.Entity<Location>(entity =>
        {
            entity.HasKey(e => e.LocationId).HasName("PK__Location__E7FEA49770FEAF76");

            entity.ToTable("Location");

            entity.Property(e => e.LocationId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.LocationName).IsRequired();
        });

        modelBuilder.Entity<MansionsPoint>(entity =>
        {
            entity.HasKey(e => e.MansionsType).HasName("PK__Mansions__1D5CE3F73B5F395C");

            entity.ToTable("MansionsPoint");

            entity.Property(e => e.MansionsType)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Master>(entity =>
        {
            entity.HasKey(e => e.MasterId).HasName("PK__Master__F6B782243BB994A4");

            entity.ToTable("Master");

            entity.Property(e => e.MasterId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.AccountId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.Experience).HasMaxLength(50);
            entity.Property(e => e.Expertise).HasMaxLength(255);
            entity.Property(e => e.ImageUrl).HasMaxLength(255);
            entity.Property(e => e.LinkMeet).HasMaxLength(255);
            entity.Property(e => e.MasterName).HasMaxLength(100);
            entity.Property(e => e.ServiceType).HasMaxLength(50);
            entity.Property(e => e.Title).HasMaxLength(100);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.Account).WithMany(p => p.Masters)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK__Master__AccountI__1DB06A4F");
        });

        modelBuilder.Entity<MasterSchedule>(entity =>
        {
            entity.HasKey(e => e.MasterScheduleId).HasName("PK__MasterSc__F5937CE5224CDDEE");

            entity.ToTable("MasterSchedule");

            entity.Property(e => e.MasterScheduleId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.MasterId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Status).HasMaxLength(20);
            entity.Property(e => e.Type).HasMaxLength(50);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.Master).WithMany(p => p.MasterSchedules)
                .HasForeignKey(d => d.MasterId)
                .HasConstraintName("FK__MasterSch__Maste__1EA48E88");
        });

        modelBuilder.Entity<Membership>(entity =>
        {
            entity.HasKey(e => e.MembershipId).HasName("PK__Membersh__92A78679AE20C01F");

            entity.ToTable("Membership");

            entity.Property(e => e.MembershipId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.Discount).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.MembershipName).HasMaxLength(50);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Order__C3905BCF8071FD96");

            entity.ToTable("Order");

            entity.Property(e => e.OrderId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.CustomerId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Note).IsRequired();
            entity.Property(e => e.OrderCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PaymentDate).HasColumnType("datetime");
            entity.Property(e => e.PaymentId)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.PaymentReference)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.ServiceId)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ServiceType).HasMaxLength(255);
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.Customer).WithMany(p => p.Orders)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Order_Customer");
        });

        modelBuilder.Entity<Question>(entity =>
        {
            entity.HasKey(e => e.QuestionId).HasName("PK__Question__0DC06FAC7AA7D03E");

            entity.ToTable("Question");

            entity.Property(e => e.QuestionId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateAt).HasColumnName("Create_At");
            entity.Property(e => e.Point).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.QuestionText).HasColumnName("Question_Text");
            entity.Property(e => e.QuestionType)
                .HasMaxLength(50)
                .HasColumnName("Question_Type");
            entity.Property(e => e.QuizId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.UpdateAt)
                .HasColumnType("datetime")
                .HasColumnName("Update_At");

            entity.HasOne(d => d.Quiz).WithMany(p => p.Questions)
                .HasForeignKey(d => d.QuizId)
                .HasConstraintName("FK__Question__QuizId__208CD6FA");
        });

        modelBuilder.Entity<Quiz>(entity =>
        {
            entity.HasKey(e => e.QuizId).HasName("PK__Quiz__8B42AE8EA87146BD");

            entity.ToTable("Quiz");

            entity.Property(e => e.QuizId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CourseId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateAt).HasColumnName("Create_At");
            entity.Property(e => e.CreateBy)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("Create_By");
            entity.Property(e => e.Score).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Title).HasMaxLength(100);
            entity.Property(e => e.UpdateAt)
                .HasColumnType("datetime")
                .HasColumnName("Update_At");

            entity.HasOne(d => d.Course).WithMany(p => p.Quizzes)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("FK__Quiz__CourseId__2180FB33");

            entity.HasOne(d => d.CreateByNavigation).WithMany(p => p.Quizzes)
                .HasForeignKey(d => d.CreateBy)
                .HasConstraintName("FK__Quiz__Create_By__22751F6C");
        });

        modelBuilder.Entity<RegisterAttend>(entity =>
        {
            entity.HasKey(e => e.AttendId).HasName("PK__Register__FDE0E82408F1C975");

            entity.ToTable("RegisterAttend");

            entity.Property(e => e.AttendId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CustomerId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.GroupId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Status).HasMaxLength(20);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
            entity.Property(e => e.WorkshopId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();

            entity.HasOne(d => d.Customer).WithMany(p => p.RegisterAttends)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK__RegisterA__Custo__236943A5");

            entity.HasOne(d => d.Workshop).WithMany(p => p.RegisterAttends)
                .HasForeignKey(d => d.WorkshopId)
                .HasConstraintName("FK__RegisterA__Works__245D67DE");
        });

        modelBuilder.Entity<RegisterCourse>(entity =>
        {
            entity.HasKey(e => e.EnrollCourseId).HasName("PK__Register__2FE697914FBDB937");

            entity.ToTable("RegisterCourse");

            entity.Property(e => e.EnrollCourseId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CourseId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.CustomerId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.EnrollCertId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.EnrollQuizId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Percentage).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Rating).HasColumnType("decimal(3, 2)");
            entity.Property(e => e.Status).HasMaxLength(20);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.Course).WithMany(p => p.RegisterCourses)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("FK__RegisterC__Cours__25518C17");

            entity.HasOne(d => d.Customer).WithMany(p => p.RegisterCourses)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_RegisterCourse_Customer");

            entity.HasOne(d => d.EnrollCert).WithMany(p => p.RegisterCourses)
                .HasForeignKey(d => d.EnrollCertId)
                .HasConstraintName("FK__RegisterC__Enrol__2645B050");

            entity.HasOne(d => d.EnrollQuiz).WithMany(p => p.RegisterCourses)
                .HasForeignKey(d => d.EnrollQuizId)
                .HasConstraintName("FK__RegisterC__Enrol__2739D489");
        });

        modelBuilder.Entity<Shape>(entity =>
        {
            entity.HasKey(e => e.ShapeId).HasName("PK__Shape__70FC838186482019");

            entity.ToTable("Shape");

            entity.Property(e => e.ShapeId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.Element).HasMaxLength(20);
            entity.Property(e => e.ShapeName).HasMaxLength(50);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<VarietyColor>(entity =>
        {
            entity.HasKey(e => new { e.KoiVarietyId, e.ColorId }).HasName("PK__VarietyC__5C078AC6DEF64903");

            entity.ToTable("VarietyColor");

            entity.Property(e => e.KoiVarietyId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("KoiVarietyID");
            entity.Property(e => e.ColorId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Percentage).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Color).WithMany(p => p.VarietyColors)
                .HasForeignKey(d => d.ColorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VarietyCo__Color__29221CFB");

            entity.HasOne(d => d.KoiVariety).WithMany(p => p.VarietyColors)
                .HasForeignKey(d => d.KoiVarietyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VarietyCo__KoiVa__2A164134");
        });

        modelBuilder.Entity<WorkShop>(entity =>
        {
            entity.HasKey(e => e.WorkshopId).HasName("PK__WorkShop__7A008C0ABEA4ABD1");

            entity.ToTable("WorkShop");

            entity.Property(e => e.WorkshopId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreateBy)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ImageUrl).HasMaxLength(255);
            entity.Property(e => e.LocationId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.MasterId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.MasterScheduleId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Status).HasMaxLength(20);
            entity.Property(e => e.Trending).HasDefaultValue(false);
            entity.Property(e => e.UpdateAt).HasColumnType("datetime");
            entity.Property(e => e.WorkshopName).HasMaxLength(100);

            entity.HasOne(d => d.Location).WithMany(p => p.WorkShops)
                .HasForeignKey(d => d.LocationId)
                .HasConstraintName("FK_Workshop_Location");

            entity.HasOne(d => d.Master).WithMany(p => p.WorkShops)
                .HasForeignKey(d => d.MasterId)
                .HasConstraintName("FK__WorkShop__Master__2B0A656D");

            entity.HasOne(d => d.MasterSchedule).WithMany(p => p.WorkShops)
                .HasForeignKey(d => d.MasterScheduleId)
                .HasConstraintName("FK_Workshop_MasterSchedule");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}