// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class KoiPond
{
    public string KoiPondId { get; set; }

    public string ShapeId { get; set; }

    public string PondName { get; set; }

    public string Introduction { get; set; }

    public string Description { get; set; }

    public string ImageUrl { get; set; }

    public virtual Shape Shape { get; set; }
}