// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class KoiVariety
{
    public string KoiVarietyId { get; set; }

    public string Description { get; set; }

    public string VarietyName { get; set; }

    public virtual ICollection<VarietyColor> VarietyColors { get; set; } = new List<VarietyColor>();
}