// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Location
{
    public string LocationId { get; set; }

    public string LocationName { get; set; }

    public virtual ICollection<WorkShop> WorkShops { get; set; } = new List<WorkShop>();
}