// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Master
{
    public string MasterId { get; set; }

    public string MasterName { get; set; }

    public byte? Rating { get; set; }

    public string Title { get; set; }

    public string ServiceType { get; set; }

    public string Expertise { get; set; }

    public string Experience { get; set; }

    public string Biography { get; set; }

    public string AccountId { get; set; }

    public string ImageUrl { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<BookingOffline> BookingOfflines { get; set; } = new List<BookingOffline>();

    public virtual ICollection<BookingOnline> BookingOnlines { get; set; } = new List<BookingOnline>();

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    public virtual ICollection<MasterSchedule> MasterSchedules { get; set; } = new List<MasterSchedule>();

    public virtual ICollection<Quiz> Quizzes { get; set; } = new List<Quiz>();

    public virtual ICollection<WorkShop> WorkShops { get; set; } = new List<WorkShop>();
}