// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class MasterSchedule
{
    public string MasterScheduleId { get; set; }

    public string MasterId { get; set; }

    public DateOnly? Date { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public string Type { get; set; }

    public string Status { get; set; }

    public virtual Master Master { get; set; }
}