// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Membership
{
    public string MembershipId { get; set; }

    public string MembershipName { get; set; }

    public DateOnly? Limit { get; set; }

    public decimal? Discount { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();
}