// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Quiz
{
    public string QuizId { get; set; }

    public string CourseId { get; set; }

    public string Title { get; set; }

    public string CreateBy { get; set; }

    public DateTime? CreateAt { get; set; }

    public decimal? Score { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual Course Course { get; set; }

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    public virtual Master CreateByNavigation { get; set; }

    public virtual ICollection<EnrollQuiz> EnrollQuizzes { get; set; } = new List<EnrollQuiz>();

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}