// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Transaction
{
    public string TransactionId { get; set; }

    public string TransactionType { get; set; }

    public string DocNo { get; set; }

    public string TransactionName { get; set; }
}