// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class VarietyColor
{
    public string KoiVarietyId { get; set; }

    public string ColorId { get; set; }

    public decimal? Percentage { get; set; }

    public virtual Color Color { get; set; }

    public virtual KoiVariety KoiVariety { get; set; }
}