// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Wallet
{
    public string WalletId { get; set; }

    public string CustomerId { get; set; }

    public decimal? Balance { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<WalletTransaction> WalletTransactions { get; set; } = new List<WalletTransaction>();
}